-- ============================================================
-- MAR DE SAN CIPRIÁN
-- 001_create_socios.sql
--
-- Crea la tabla de socios de la Asociación.
-- Los datos personales permanecen cerrados mediante RLS.
-- ============================================================

-- Secuencia independiente para la numeración de socios.
create sequence if not exists public.socios_numero_seq
  start with 1
  increment by 1;

create table if not exists public.socios (
  id bigint generated by default as identity primary key,

  numero_socio text not null unique
    default (
      'MSC-' ||
      lpad(nextval('public.socios_numero_seq')::text, 6, '0')
    ),

  nombre text not null,
  apellidos text not null,
  email text not null,

  dni_nie text,
  fecha_nacimiento date,
  direccion text,
  codigo_postal text,
  localidad text not null,
  provincia text not null,
  pais text not null default 'España',
  telefono text,

  acepta_privacidad boolean not null
    check (acepta_privacidad = true),

  fecha_inscripcion date not null default current_date,
  activo boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Evita correos duplicados aunque cambien mayúsculas/minúsculas.
create unique index if not exists socios_email_unico
  on public.socios (lower(trim(email)));

-- Evita DNI/NIE duplicados cuando se haya facilitado uno.
create unique index if not exists socios_dni_nie_unico
  on public.socios (upper(trim(dni_nie)))
  where dni_nie is not null and trim(dni_nie) <> '';

-- Índices para búsquedas habituales en administración.
create index if not exists socios_apellidos_idx
  on public.socios (apellidos);

create index if not exists socios_localidad_idx
  on public.socios (localidad);

create index if not exists socios_fecha_inscripcion_idx
  on public.socios (fecha_inscripcion);

-- Actualiza automáticamente updated_at al modificar un registro.
create or replace function public.actualizar_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists socios_actualizar_updated_at
  on public.socios;

create trigger socios_actualizar_updated_at
before update on public.socios
for each row
execute function public.actualizar_updated_at();

-- Protección de datos: tabla cerrada por defecto.
alter table public.socios enable row level security;

-- No se crean políticas públicas.
-- La inscripción se realizará más adelante desde una ruta segura
-- del servidor de Next.js, nunca exponiendo claves privadas.