-- ============================================================
-- MAR DE SAN CIPRIÁN
-- 006_create_noticias.sql
--
-- Crea el módulo de noticias de la Asociación.
--
-- Las noticias publicadas podrán consultarse desde la web
-- pública. Los borradores y la gestión completa permanecerán
-- restringidos a usuarios autenticados.
-- ============================================================

create table if not exists public.noticias (
  id bigint generated by default as identity primary key,

  titulo_gl text not null,
  titulo_es text not null,

  resumen_gl text not null,
  resumen_es text not null,

  contenido_gl text not null,
  contenido_es text not null,

  slug text not null unique,

  imagen_url text,
  imagen_alt_gl text,
  imagen_alt_es text,

  publicada boolean not null default false,

  fecha_publicacion timestamptz,
  autor_id uuid references auth.users(id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint noticias_titulo_gl_longitud
    check (char_length(trim(titulo_gl)) between 3 and 200),

  constraint noticias_titulo_es_longitud
    check (char_length(trim(titulo_es)) between 3 and 200),

  constraint noticias_resumen_gl_longitud
    check (char_length(trim(resumen_gl)) between 10 and 500),

  constraint noticias_resumen_es_longitud
    check (char_length(trim(resumen_es)) between 10 and 500),

  constraint noticias_contenido_gl_longitud
    check (char_length(trim(contenido_gl)) >= 20),

  constraint noticias_contenido_es_longitud
    check (char_length(trim(contenido_es)) >= 20),

  constraint noticias_slug_formato
    check (
      slug = lower(slug)
      and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),

  constraint noticias_fecha_publicacion
    check (
      publicada = false
      or fecha_publicacion is not null
    )
);

-- Índices para consultas habituales.

create index if not exists noticias_publicada_idx
  on public.noticias (publicada);

create index if not exists noticias_fecha_publicacion_idx
  on public.noticias (fecha_publicacion desc);

create index if not exists noticias_created_at_idx
  on public.noticias (created_at desc);

-- Actualización automática de updated_at.

drop trigger if exists noticias_actualizar_updated_at
  on public.noticias;

create trigger noticias_actualizar_updated_at
before update on public.noticias
for each row
execute function public.actualizar_updated_at();

-- Activación de Row Level Security.

alter table public.noticias enable row level security;

-- ============================================================
-- PERMISOS
-- ============================================================

grant select on table public.noticias
to anon, authenticated;

grant insert, update, delete on table public.noticias
to authenticated;

grant usage on sequence public.noticias_id_seq
to authenticated;

-- ============================================================
-- LECTURA PÚBLICA
-- ============================================================

drop policy if exists "Lectura pública de noticias publicadas"
on public.noticias;

create policy "Lectura pública de noticias publicadas"
on public.noticias
for select
to anon
using (
  publicada = true
  and fecha_publicacion is not null
  and fecha_publicacion <= now()
);

-- ============================================================
-- LECTURA PRIVADA
-- ============================================================

drop policy if exists "Consulta privada de noticias"
on public.noticias;

create policy "Consulta privada de noticias"
on public.noticias
for select
to authenticated
using (
  auth.uid() is not null
);

-- ============================================================
-- CREACIÓN PRIVADA
-- ============================================================

drop policy if exists "Alta privada de noticias"
on public.noticias;

create policy "Alta privada de noticias"
on public.noticias
for insert
to authenticated
with check (
  auth.uid() is not null
  and autor_id = auth.uid()
  and char_length(trim(titulo_gl)) between 3 and 200
  and char_length(trim(titulo_es)) between 3 and 200
  and char_length(trim(resumen_gl)) between 10 and 500
  and char_length(trim(resumen_es)) between 10 and 500
  and char_length(trim(contenido_gl)) >= 20
  and char_length(trim(contenido_es)) >= 20
  and slug = lower(slug)
  and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  and (
    publicada = false
    or fecha_publicacion is not null
  )
);

-- ============================================================
-- EDICIÓN PRIVADA
-- ============================================================

drop policy if exists "Edición privada de noticias"
on public.noticias;

create policy "Edición privada de noticias"
on public.noticias
for update
to authenticated
using (
  auth.uid() is not null
)
with check (
  auth.uid() is not null
  and char_length(trim(titulo_gl)) between 3 and 200
  and char_length(trim(titulo_es)) between 3 and 200
  and char_length(trim(resumen_gl)) between 10 and 500
  and char_length(trim(resumen_es)) between 10 and 500
  and char_length(trim(contenido_gl)) >= 20
  and char_length(trim(contenido_es)) >= 20
  and slug = lower(slug)
  and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  and (
    publicada = false
    or fecha_publicacion is not null
  )
);

-- ============================================================
-- ELIMINACIÓN PRIVADA
-- ============================================================

drop policy if exists "Eliminación privada de noticias"
on public.noticias;

create policy "Eliminación privada de noticias"
on public.noticias
for delete
to authenticated
using (
  auth.uid() is not null
);