-- ============================================================
-- MAR DE SAN CIPRIÁN
-- 007_create_galeria.sql
--
-- Crea la estructura de datos de la Galería multimedia.
--
-- Los archivos físicos se almacenan en Supabase Storage
-- dentro del bucket público "galeria".
--
-- Las tablas guardan la información descriptiva,
-- organización y estado de publicación.
-- ============================================================


-- ============================================================
-- ÁLBUMES
-- ============================================================

create table if not exists public.galeria_albumes (
  id bigint generated by default as identity primary key,

  titulo_gl text not null,
  titulo_es text not null,

  descripcion_gl text,
  descripcion_es text,

  slug text not null unique,

  portada_url text,

  fecha_evento date,

  publicado boolean not null default false,
  destacado boolean not null default false,

  orden integer not null default 0,

  autor_id uuid references auth.users(id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint galeria_album_titulo_gl_longitud
    check (char_length(trim(titulo_gl)) between 2 and 200),

  constraint galeria_album_titulo_es_longitud
    check (char_length(trim(titulo_es)) between 2 and 200),

  constraint galeria_album_slug_formato
    check (
      slug = lower(slug)
      and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),

  constraint galeria_album_orden_valido
    check (orden >= 0)
);


-- ============================================================
-- ELEMENTOS MULTIMEDIA
-- ============================================================

create table if not exists public.galeria_elementos (
  id bigint generated by default as identity primary key,

  album_id bigint
    references public.galeria_albumes(id)
    on delete cascade,

  tipo text not null,

  archivo_path text not null unique,
  archivo_url text not null,

  nombre_archivo text not null,
  mime_type text,

  tamano_bytes bigint,

  titulo_gl text,
  titulo_es text,

  descripcion_gl text,
  descripcion_es text,

  alt_gl text,
  alt_es text,

  fecha_captura date,

  autor_fotografia text,

  publicado boolean not null default false,
  destacado boolean not null default false,

  orden integer not null default 0,

  usuario_id uuid references auth.users(id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint galeria_elemento_tipo_valido
    check (tipo in ('imagen', 'video')),

  constraint galeria_elemento_tamano_valido
    check (
      tamano_bytes is null
      or tamano_bytes >= 0
    ),

  constraint galeria_elemento_orden_valido
    check (orden >= 0)
);


-- ============================================================
-- ÍNDICES
-- ============================================================

create index if not exists galeria_albumes_publicado_idx
  on public.galeria_albumes (publicado);

create index if not exists galeria_albumes_fecha_evento_idx
  on public.galeria_albumes (fecha_evento desc);

create index if not exists galeria_albumes_orden_idx
  on public.galeria_albumes (orden);

create index if not exists galeria_elementos_album_idx
  on public.galeria_elementos (album_id);

create index if not exists galeria_elementos_tipo_idx
  on public.galeria_elementos (tipo);

create index if not exists galeria_elementos_publicado_idx
  on public.galeria_elementos (publicado);

create index if not exists galeria_elementos_orden_idx
  on public.galeria_elementos (orden);


-- ============================================================
-- UPDATED_AT AUTOMÁTICO
-- ============================================================

drop trigger if exists galeria_albumes_actualizar_updated_at
  on public.galeria_albumes;

create trigger galeria_albumes_actualizar_updated_at
before update on public.galeria_albumes
for each row
execute function public.actualizar_updated_at();


drop trigger if exists galeria_elementos_actualizar_updated_at
  on public.galeria_elementos;

create trigger galeria_elementos_actualizar_updated_at
before update on public.galeria_elementos
for each row
execute function public.actualizar_updated_at();


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.galeria_albumes
enable row level security;

alter table public.galeria_elementos
enable row level security;


-- ============================================================
-- PERMISOS SQL
-- ============================================================

grant select
on table public.galeria_albumes
to anon, authenticated;

grant select
on table public.galeria_elementos
to anon, authenticated;

grant insert, update, delete
on table public.galeria_albumes
to authenticated;

grant insert, update, delete
on table public.galeria_elementos
to authenticated;

grant usage
on sequence public.galeria_albumes_id_seq
to authenticated;

grant usage
on sequence public.galeria_elementos_id_seq
to authenticated;


-- ============================================================
-- LECTURA PÚBLICA DE ÁLBUMES PUBLICADOS
-- ============================================================

drop policy if exists "Lectura pública de álbumes publicados"
on public.galeria_albumes;

create policy "Lectura pública de álbumes publicados"
on public.galeria_albumes
for select
to anon
using (
  publicado = true
);


-- ============================================================
-- LECTURA PRIVADA DE ÁLBUMES
-- ============================================================

drop policy if exists "Consulta privada de álbumes"
on public.galeria_albumes;

create policy "Consulta privada de álbumes"
on public.galeria_albumes
for select
to authenticated
using (
  auth.uid() is not null
);


-- ============================================================
-- ALTA PRIVADA DE ÁLBUMES
-- ============================================================

drop policy if exists "Alta privada de álbumes"
on public.galeria_albumes;

create policy "Alta privada de álbumes"
on public.galeria_albumes
for insert
to authenticated
with check (
  auth.uid() is not null
  and autor_id = auth.uid()
);


-- ============================================================
-- EDICIÓN PRIVADA DE ÁLBUMES
-- ============================================================

drop policy if exists "Edición privada de álbumes"
on public.galeria_albumes;

create policy "Edición privada de álbumes"
on public.galeria_albumes
for update
to authenticated
using (
  auth.uid() is not null
)
with check (
  auth.uid() is not null
);


-- ============================================================
-- ELIMINACIÓN PRIVADA DE ÁLBUMES
-- ============================================================

drop policy if exists "Eliminación privada de álbumes"
on public.galeria_albumes;

create policy "Eliminación privada de álbumes"
on public.galeria_albumes
for delete
to authenticated
using (
  auth.uid() is not null
);


-- ============================================================
-- LECTURA PÚBLICA DE ELEMENTOS PUBLICADOS
-- ============================================================

drop policy if exists "Lectura pública de elementos publicados"
on public.galeria_elementos;

create policy "Lectura pública de elementos publicados"
on public.galeria_elementos
for select
to anon
using (
  publicado = true
);


-- ============================================================
-- LECTURA PRIVADA DE ELEMENTOS
-- ============================================================

drop policy if exists "Consulta privada de elementos"
on public.galeria_elementos;

create policy "Consulta privada de elementos"
on public.galeria_elementos
for select
to authenticated
using (
  auth.uid() is not null
);


-- ============================================================
-- ALTA PRIVADA DE ELEMENTOS
-- ============================================================

drop policy if exists "Alta privada de elementos"
on public.galeria_elementos;

create policy "Alta privada de elementos"
on public.galeria_elementos
for insert
to authenticated
with check (
  auth.uid() is not null
  and usuario_id = auth.uid()
);


-- ============================================================
-- EDICIÓN PRIVADA DE ELEMENTOS
-- ============================================================

drop policy if exists "Edición privada de elementos"
on public.galeria_elementos;

create policy "Edición privada de elementos"
on public.galeria_elementos
for update
to authenticated
using (
  auth.uid() is not null
)
with check (
  auth.uid() is not null
);


-- ============================================================
-- ELIMINACIÓN PRIVADA DE ELEMENTOS
-- ============================================================

drop policy if exists "Eliminación privada de elementos"
on public.galeria_elementos;

create policy "Eliminación privada de elementos"
on public.galeria_elementos
for delete
to authenticated
using (
  auth.uid() is not null
);